// Copyright (c) 2021 Fraunhofer AISEC
// Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: grpcapi.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttestationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Cached        []string               `protobuf:"bytes,3,rep,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestationRequest) Reset() {
	*x = AttestationRequest{}
	mi := &file_grpcapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationRequest) ProtoMessage() {}

func (x *AttestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationRequest.ProtoReflect.Descriptor instead.
func (*AttestationRequest) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{0}
}

func (x *AttestationRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AttestationRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *AttestationRequest) GetCached() []string {
	if x != nil {
		return x.Cached
	}
	return nil
}

type AttestationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Report        []byte                 `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestationResponse) Reset() {
	*x = AttestationResponse{}
	mi := &file_grpcapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationResponse) ProtoMessage() {}

func (x *AttestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationResponse.ProtoReflect.Descriptor instead.
func (*AttestationResponse) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{1}
}

func (x *AttestationResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AttestationResponse) GetReport() []byte {
	if x != nil {
		return x.Report
	}
	return nil
}

type VerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Report        []byte                 `protobuf:"bytes,3,opt,name=report,proto3" json:"report,omitempty"`
	Peer          string                 `protobuf:"bytes,7,opt,name=peer,proto3" json:"peer,omitempty"`
	Policies      []byte                 `protobuf:"bytes,9,opt,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationRequest) Reset() {
	*x = VerificationRequest{}
	mi := &file_grpcapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationRequest) ProtoMessage() {}

func (x *VerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationRequest.ProtoReflect.Descriptor instead.
func (*VerificationRequest) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{2}
}

func (x *VerificationRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VerificationRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *VerificationRequest) GetReport() []byte {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *VerificationRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *VerificationRequest) GetPolicies() []byte {
	if x != nil {
		return x.Policies
	}
	return nil
}

type VerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Result        []byte                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationResponse) Reset() {
	*x = VerificationResponse{}
	mi := &file_grpcapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationResponse) ProtoMessage() {}

func (x *VerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationResponse.ProtoReflect.Descriptor instead.
func (*VerificationResponse) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{3}
}

func (x *VerificationResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VerificationResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type TLSCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	KeyConfig     *TLSKeyConfig          `protobuf:"bytes,2,opt,name=key_config,json=keyConfig,proto3" json:"key_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSCreateRequest) Reset() {
	*x = TLSCreateRequest{}
	mi := &file_grpcapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSCreateRequest) ProtoMessage() {}

func (x *TLSCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSCreateRequest.ProtoReflect.Descriptor instead.
func (*TLSCreateRequest) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{4}
}

func (x *TLSCreateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TLSCreateRequest) GetKeyConfig() *TLSKeyConfig {
	if x != nil {
		return x.KeyConfig
	}
	return nil
}

type TLSCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSCreateResponse) Reset() {
	*x = TLSCreateResponse{}
	mi := &file_grpcapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSCreateResponse) ProtoMessage() {}

func (x *TLSCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSCreateResponse.ProtoReflect.Descriptor instead.
func (*TLSCreateResponse) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{5}
}

func (x *TLSCreateResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TLSCreateResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type TLSKeyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Alg           string                 `protobuf:"bytes,2,opt,name=alg,proto3" json:"alg,omitempty"`
	Cn            string                 `protobuf:"bytes,3,opt,name=cn,proto3" json:"cn,omitempty"`
	DnsNames      []string               `protobuf:"bytes,4,rep,name=dns_names,json=dnsNames,proto3" json:"dns_names,omitempty"`
	IpAddresses   []string               `protobuf:"bytes,5,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSKeyConfig) Reset() {
	*x = TLSKeyConfig{}
	mi := &file_grpcapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSKeyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSKeyConfig) ProtoMessage() {}

func (x *TLSKeyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSKeyConfig.ProtoReflect.Descriptor instead.
func (*TLSKeyConfig) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{6}
}

func (x *TLSKeyConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TLSKeyConfig) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *TLSKeyConfig) GetCn() string {
	if x != nil {
		return x.Cn
	}
	return ""
}

func (x *TLSKeyConfig) GetDnsNames() []string {
	if x != nil {
		return x.DnsNames
	}
	return nil
}

func (x *TLSKeyConfig) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

type TLSSignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	HashAlg       string                 `protobuf:"bytes,4,opt,name=hash_alg,json=hashAlg,proto3" json:"hash_alg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSSignRequest) Reset() {
	*x = TLSSignRequest{}
	mi := &file_grpcapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSSignRequest) ProtoMessage() {}

func (x *TLSSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSSignRequest.ProtoReflect.Descriptor instead.
func (*TLSSignRequest) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{7}
}

func (x *TLSSignRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TLSSignRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *TLSSignRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *TLSSignRequest) GetHashAlg() string {
	if x != nil {
		return x.HashAlg
	}
	return ""
}

type TLSSignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	SignedContent []byte                 `protobuf:"bytes,2,opt,name=signed_content,json=signedContent,proto3" json:"signed_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSSignResponse) Reset() {
	*x = TLSSignResponse{}
	mi := &file_grpcapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSSignResponse) ProtoMessage() {}

func (x *TLSSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSSignResponse.ProtoReflect.Descriptor instead.
func (*TLSSignResponse) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{8}
}

func (x *TLSSignResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TLSSignResponse) GetSignedContent() []byte {
	if x != nil {
		return x.SignedContent
	}
	return nil
}

type TLSCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSCertRequest) Reset() {
	*x = TLSCertRequest{}
	mi := &file_grpcapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSCertRequest) ProtoMessage() {}

func (x *TLSCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSCertRequest.ProtoReflect.Descriptor instead.
func (*TLSCertRequest) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{9}
}

func (x *TLSCertRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TLSCertRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type TLSCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Certificate   [][]byte               `protobuf:"bytes,2,rep,name=certificate,proto3" json:"certificate,omitempty"` // PEM encoded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSCertResponse) Reset() {
	*x = TLSCertResponse{}
	mi := &file_grpcapi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSCertResponse) ProtoMessage() {}

func (x *TLSCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSCertResponse.ProtoReflect.Descriptor instead.
func (*TLSCertResponse) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{10}
}

func (x *TLSCertResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TLSCertResponse) GetCertificate() [][]byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type PeerCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Peer          string                 `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerCacheRequest) Reset() {
	*x = PeerCacheRequest{}
	mi := &file_grpcapi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerCacheRequest) ProtoMessage() {}

func (x *PeerCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerCacheRequest.ProtoReflect.Descriptor instead.
func (*PeerCacheRequest) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{11}
}

func (x *PeerCacheRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PeerCacheRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

type PeerCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Cache         []string               `protobuf:"bytes,2,rep,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerCacheResponse) Reset() {
	*x = PeerCacheResponse{}
	mi := &file_grpcapi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerCacheResponse) ProtoMessage() {}

func (x *PeerCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerCacheResponse.ProtoReflect.Descriptor instead.
func (*PeerCacheResponse) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{12}
}

func (x *PeerCacheResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PeerCacheResponse) GetCache() []string {
	if x != nil {
		return x.Cache
	}
	return nil
}

type MeasureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	MeasureEvent  *MeasureEvent          `protobuf:"bytes,2,opt,name=measure_event,json=measureEvent,proto3" json:"measure_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasureRequest) Reset() {
	*x = MeasureRequest{}
	mi := &file_grpcapi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasureRequest) ProtoMessage() {}

func (x *MeasureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasureRequest.ProtoReflect.Descriptor instead.
func (*MeasureRequest) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{13}
}

func (x *MeasureRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MeasureRequest) GetMeasureEvent() *MeasureEvent {
	if x != nil {
		return x.MeasureEvent
	}
	return nil
}

type MeasureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasureResponse) Reset() {
	*x = MeasureResponse{}
	mi := &file_grpcapi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasureResponse) ProtoMessage() {}

func (x *MeasureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasureResponse.ProtoReflect.Descriptor instead.
func (*MeasureResponse) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{14}
}

func (x *MeasureResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MeasureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateCertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCertsRequest) Reset() {
	*x = UpdateCertsRequest{}
	mi := &file_grpcapi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCertsRequest) ProtoMessage() {}

func (x *UpdateCertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCertsRequest.ProtoReflect.Descriptor instead.
func (*UpdateCertsRequest) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateCertsRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type UpdateCertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCertsResponse) Reset() {
	*x = UpdateCertsResponse{}
	mi := &file_grpcapi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCertsResponse) ProtoMessage() {}

func (x *UpdateCertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCertsResponse.ProtoReflect.Descriptor instead.
func (*UpdateCertsResponse) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateCertsResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateCertsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetadataRequest) Reset() {
	*x = UpdateMetadataRequest{}
	mi := &file_grpcapi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataRequest) ProtoMessage() {}

func (x *UpdateMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetadataRequest) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateMetadataRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type UpdateMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetadataResponse) Reset() {
	*x = UpdateMetadataResponse{}
	mi := &file_grpcapi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataResponse) ProtoMessage() {}

func (x *UpdateMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetadataResponse) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateMetadataResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateMetadataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MeasureEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        []byte                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	EventName     string                 `protobuf:"bytes,3,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	CtrData       *CtrData               `protobuf:"bytes,4,opt,name=ctr_data,json=ctrData,proto3" json:"ctr_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasureEvent) Reset() {
	*x = MeasureEvent{}
	mi := &file_grpcapi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasureEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasureEvent) ProtoMessage() {}

func (x *MeasureEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasureEvent.ProtoReflect.Descriptor instead.
func (*MeasureEvent) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{19}
}

func (x *MeasureEvent) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *MeasureEvent) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MeasureEvent) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *MeasureEvent) GetCtrData() *CtrData {
	if x != nil {
		return x.CtrData
	}
	return nil
}

type CtrData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigSha256  []byte                 `protobuf:"bytes,1,opt,name=config_sha256,json=configSha256,proto3" json:"config_sha256,omitempty"`
	RootfsSha256  []byte                 `protobuf:"bytes,2,opt,name=rootfs_sha256,json=rootfsSha256,proto3" json:"rootfs_sha256,omitempty"`
	OciSpec       []byte                 `protobuf:"bytes,3,opt,name=oci_spec,json=ociSpec,proto3" json:"oci_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtrData) Reset() {
	*x = CtrData{}
	mi := &file_grpcapi_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtrData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtrData) ProtoMessage() {}

func (x *CtrData) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtrData.ProtoReflect.Descriptor instead.
func (*CtrData) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{20}
}

func (x *CtrData) GetConfigSha256() []byte {
	if x != nil {
		return x.ConfigSha256
	}
	return nil
}

func (x *CtrData) GetRootfsSha256() []byte {
	if x != nil {
		return x.RootfsSha256
	}
	return nil
}

func (x *CtrData) GetOciSpec() []byte {
	if x != nil {
		return x.OciSpec
	}
	return nil
}

var File_grpcapi_proto protoreflect.FileDescriptor

const file_grpcapi_proto_rawDesc = "" +
	"\n" +
	"\rgrpcapi.proto\x12\agrpcapi\"\\\n" +
	"\x12AttestationRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x16\n" +
	"\x06cached\x18\x03 \x03(\tR\x06cached\"G\n" +
	"\x13AttestationResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06report\x18\x02 \x01(\fR\x06report\"\x8d\x01\n" +
	"\x13VerificationRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x16\n" +
	"\x06report\x18\x03 \x01(\fR\x06report\x12\x12\n" +
	"\x04peer\x18\a \x01(\tR\x04peer\x12\x1a\n" +
	"\bpolicies\x18\t \x01(\fR\bpolicies\"H\n" +
	"\x14VerificationResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06result\"b\n" +
	"\x10TLSCreateRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x124\n" +
	"\n" +
	"key_config\x18\x02 \x01(\v2\x15.grpcapi.TLSKeyConfigR\tkeyConfig\"D\n" +
	"\x11TLSCreateResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\"\x84\x01\n" +
	"\fTLSKeyConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03alg\x18\x02 \x01(\tR\x03alg\x12\x0e\n" +
	"\x02cn\x18\x03 \x01(\tR\x02cn\x12\x1b\n" +
	"\tdns_names\x18\x04 \x03(\tR\bdnsNames\x12!\n" +
	"\fip_addresses\x18\x05 \x03(\tR\vipAddresses\"v\n" +
	"\x0eTLSSignRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x19\n" +
	"\bhash_alg\x18\x04 \x01(\tR\ahashAlg\"R\n" +
	"\x0fTLSSignResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0esigned_content\x18\x02 \x01(\fR\rsignedContent\"A\n" +
	"\x0eTLSCertRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\"M\n" +
	"\x0fTLSCertResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12 \n" +
	"\vcertificate\x18\x02 \x03(\fR\vcertificate\"@\n" +
	"\x10PeerCacheRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04peer\x18\x02 \x01(\tR\x04peer\"C\n" +
	"\x11PeerCacheResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x14\n" +
	"\x05cache\x18\x02 \x03(\tR\x05cache\"f\n" +
	"\x0eMeasureRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12:\n" +
	"\rmeasure_event\x18\x02 \x01(\v2\x15.grpcapi.MeasureEventR\fmeasureEvent\"E\n" +
	"\x0fMeasureResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\".\n" +
	"\x12UpdateCertsRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"I\n" +
	"\x13UpdateCertsResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"1\n" +
	"\x15UpdateMetadataRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"L\n" +
	"\x16UpdateMetadataResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x88\x01\n" +
	"\fMeasureEvent\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\fR\x06sha256\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x1d\n" +
	"\n" +
	"event_name\x18\x03 \x01(\tR\teventName\x12+\n" +
	"\bctr_data\x18\x04 \x01(\v2\x10.grpcapi.CtrDataR\actrData\"n\n" +
	"\aCtrData\x12#\n" +
	"\rconfig_sha256\x18\x01 \x01(\fR\fconfigSha256\x12#\n" +
	"\rrootfs_sha256\x18\x02 \x01(\fR\frootfsSha256\x12\x19\n" +
	"\boci_spec\x18\x03 \x01(\fR\aociSpec2\x89\x05\n" +
	"\n" +
	"CMCService\x12E\n" +
	"\x06Attest\x12\x1b.grpcapi.AttestationRequest\x1a\x1c.grpcapi.AttestationResponse\"\x00\x12G\n" +
	"\x06Verify\x12\x1c.grpcapi.VerificationRequest\x1a\x1d.grpcapi.VerificationResponse\"\x00\x12D\n" +
	"\tTLSCreate\x12\x19.grpcapi.TLSCreateRequest\x1a\x1a.grpcapi.TLSCreateResponse\"\x00\x12>\n" +
	"\aTLSSign\x12\x17.grpcapi.TLSSignRequest\x1a\x18.grpcapi.TLSSignResponse\"\x00\x12>\n" +
	"\aTLSCert\x12\x17.grpcapi.TLSCertRequest\x1a\x18.grpcapi.TLSCertResponse\"\x00\x12D\n" +
	"\tPeerCache\x12\x19.grpcapi.PeerCacheRequest\x1a\x1a.grpcapi.PeerCacheResponse\"\x00\x12>\n" +
	"\aMeasure\x12\x17.grpcapi.MeasureRequest\x1a\x18.grpcapi.MeasureResponse\"\x00\x12J\n" +
	"\vUpdateCerts\x12\x1b.grpcapi.UpdateCertsRequest\x1a\x1c.grpcapi.UpdateCertsResponse\"\x00\x12S\n" +
	"\x0eUpdateMetadata\x12\x1e.grpcapi.UpdateMetadataRequest\x1a\x1f.grpcapi.UpdateMetadataResponse\"\x00B\fZ\n" +
	"./;grpcapib\x06proto3"

var (
	file_grpcapi_proto_rawDescOnce sync.Once
	file_grpcapi_proto_rawDescData []byte
)

func file_grpcapi_proto_rawDescGZIP() []byte {
	file_grpcapi_proto_rawDescOnce.Do(func() {
		file_grpcapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcapi_proto_rawDesc), len(file_grpcapi_proto_rawDesc)))
	})
	return file_grpcapi_proto_rawDescData
}

var file_grpcapi_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_grpcapi_proto_goTypes = []any{
	(*AttestationRequest)(nil),     // 0: grpcapi.AttestationRequest
	(*AttestationResponse)(nil),    // 1: grpcapi.AttestationResponse
	(*VerificationRequest)(nil),    // 2: grpcapi.VerificationRequest
	(*VerificationResponse)(nil),   // 3: grpcapi.VerificationResponse
	(*TLSCreateRequest)(nil),       // 4: grpcapi.TLSCreateRequest
	(*TLSCreateResponse)(nil),      // 5: grpcapi.TLSCreateResponse
	(*TLSKeyConfig)(nil),           // 6: grpcapi.TLSKeyConfig
	(*TLSSignRequest)(nil),         // 7: grpcapi.TLSSignRequest
	(*TLSSignResponse)(nil),        // 8: grpcapi.TLSSignResponse
	(*TLSCertRequest)(nil),         // 9: grpcapi.TLSCertRequest
	(*TLSCertResponse)(nil),        // 10: grpcapi.TLSCertResponse
	(*PeerCacheRequest)(nil),       // 11: grpcapi.PeerCacheRequest
	(*PeerCacheResponse)(nil),      // 12: grpcapi.PeerCacheResponse
	(*MeasureRequest)(nil),         // 13: grpcapi.MeasureRequest
	(*MeasureResponse)(nil),        // 14: grpcapi.MeasureResponse
	(*UpdateCertsRequest)(nil),     // 15: grpcapi.UpdateCertsRequest
	(*UpdateCertsResponse)(nil),    // 16: grpcapi.UpdateCertsResponse
	(*UpdateMetadataRequest)(nil),  // 17: grpcapi.UpdateMetadataRequest
	(*UpdateMetadataResponse)(nil), // 18: grpcapi.UpdateMetadataResponse
	(*MeasureEvent)(nil),           // 19: grpcapi.MeasureEvent
	(*CtrData)(nil),                // 20: grpcapi.CtrData
}
var file_grpcapi_proto_depIdxs = []int32{
	6,  // 0: grpcapi.TLSCreateRequest.key_config:type_name -> grpcapi.TLSKeyConfig
	19, // 1: grpcapi.MeasureRequest.measure_event:type_name -> grpcapi.MeasureEvent
	20, // 2: grpcapi.MeasureEvent.ctr_data:type_name -> grpcapi.CtrData
	0,  // 3: grpcapi.CMCService.Attest:input_type -> grpcapi.AttestationRequest
	2,  // 4: grpcapi.CMCService.Verify:input_type -> grpcapi.VerificationRequest
	4,  // 5: grpcapi.CMCService.TLSCreate:input_type -> grpcapi.TLSCreateRequest
	7,  // 6: grpcapi.CMCService.TLSSign:input_type -> grpcapi.TLSSignRequest
	9,  // 7: grpcapi.CMCService.TLSCert:input_type -> grpcapi.TLSCertRequest
	11, // 8: grpcapi.CMCService.PeerCache:input_type -> grpcapi.PeerCacheRequest
	13, // 9: grpcapi.CMCService.Measure:input_type -> grpcapi.MeasureRequest
	15, // 10: grpcapi.CMCService.UpdateCerts:input_type -> grpcapi.UpdateCertsRequest
	17, // 11: grpcapi.CMCService.UpdateMetadata:input_type -> grpcapi.UpdateMetadataRequest
	1,  // 12: grpcapi.CMCService.Attest:output_type -> grpcapi.AttestationResponse
	3,  // 13: grpcapi.CMCService.Verify:output_type -> grpcapi.VerificationResponse
	5,  // 14: grpcapi.CMCService.TLSCreate:output_type -> grpcapi.TLSCreateResponse
	8,  // 15: grpcapi.CMCService.TLSSign:output_type -> grpcapi.TLSSignResponse
	10, // 16: grpcapi.CMCService.TLSCert:output_type -> grpcapi.TLSCertResponse
	12, // 17: grpcapi.CMCService.PeerCache:output_type -> grpcapi.PeerCacheResponse
	14, // 18: grpcapi.CMCService.Measure:output_type -> grpcapi.MeasureResponse
	16, // 19: grpcapi.CMCService.UpdateCerts:output_type -> grpcapi.UpdateCertsResponse
	18, // 20: grpcapi.CMCService.UpdateMetadata:output_type -> grpcapi.UpdateMetadataResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_grpcapi_proto_init() }
func file_grpcapi_proto_init() {
	if File_grpcapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcapi_proto_rawDesc), len(file_grpcapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcapi_proto_goTypes,
		DependencyIndexes: file_grpcapi_proto_depIdxs,
		MessageInfos:      file_grpcapi_proto_msgTypes,
	}.Build()
	File_grpcapi_proto = out.File
	file_grpcapi_proto_goTypes = nil
	file_grpcapi_proto_depIdxs = nil
}
