// Copyright (c) 2021 Fraunhofer AISEC
// Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: cmcinterface.proto

package cmcinterface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_OK              Status = 0
	Status_FAIL            Status = 1
	Status_NOT_IMPLEMENTED Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OK",
		1: "FAIL",
		2: "NOT_IMPLEMENTED",
	}
	Status_value = map[string]int32{
		"OK":              0,
		"FAIL":            1,
		"NOT_IMPLEMENTED": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_cmcinterface_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_cmcinterface_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_cmcinterface_proto_rawDescGZIP(), []int{0}
}

type HashFunction int32

const (
	HashFunction_SHA1        HashFunction = 0
	HashFunction_SHA224      HashFunction = 1
	HashFunction_SHA256      HashFunction = 2
	HashFunction_SHA384      HashFunction = 3
	HashFunction_SHA512      HashFunction = 4
	HashFunction_MD4         HashFunction = 5
	HashFunction_MD5         HashFunction = 6
	HashFunction_MD5SHA1     HashFunction = 7
	HashFunction_RIPEMD160   HashFunction = 8
	HashFunction_SHA3_224    HashFunction = 9
	HashFunction_SHA3_256    HashFunction = 10
	HashFunction_SHA3_384    HashFunction = 11
	HashFunction_SHA3_512    HashFunction = 12
	HashFunction_SHA512_224  HashFunction = 13
	HashFunction_SHA512_256  HashFunction = 14
	HashFunction_BLAKE2s_256 HashFunction = 15
	HashFunction_BLAKE2b_256 HashFunction = 16
	HashFunction_BLAKE2b_384 HashFunction = 17
	HashFunction_BLAKE2b_512 HashFunction = 18
)

// Enum value maps for HashFunction.
var (
	HashFunction_name = map[int32]string{
		0:  "SHA1",
		1:  "SHA224",
		2:  "SHA256",
		3:  "SHA384",
		4:  "SHA512",
		5:  "MD4",
		6:  "MD5",
		7:  "MD5SHA1",
		8:  "RIPEMD160",
		9:  "SHA3_224",
		10: "SHA3_256",
		11: "SHA3_384",
		12: "SHA3_512",
		13: "SHA512_224",
		14: "SHA512_256",
		15: "BLAKE2s_256",
		16: "BLAKE2b_256",
		17: "BLAKE2b_384",
		18: "BLAKE2b_512",
	}
	HashFunction_value = map[string]int32{
		"SHA1":        0,
		"SHA224":      1,
		"SHA256":      2,
		"SHA384":      3,
		"SHA512":      4,
		"MD4":         5,
		"MD5":         6,
		"MD5SHA1":     7,
		"RIPEMD160":   8,
		"SHA3_224":    9,
		"SHA3_256":    10,
		"SHA3_384":    11,
		"SHA3_512":    12,
		"SHA512_224":  13,
		"SHA512_256":  14,
		"BLAKE2s_256": 15,
		"BLAKE2b_256": 16,
		"BLAKE2b_384": 17,
		"BLAKE2b_512": 18,
	}
)

func (x HashFunction) Enum() *HashFunction {
	p := new(HashFunction)
	*p = x
	return p
}

func (x HashFunction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashFunction) Descriptor() protoreflect.EnumDescriptor {
	return file_cmcinterface_proto_enumTypes[1].Descriptor()
}

func (HashFunction) Type() protoreflect.EnumType {
	return &file_cmcinterface_proto_enumTypes[1]
}

func (x HashFunction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HashFunction.Descriptor instead.
func (HashFunction) EnumDescriptor() ([]byte, []int) {
	return file_cmcinterface_proto_rawDescGZIP(), []int{1}
}

type PSSOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SaltLength int32 `protobuf:"varint,1,opt,name=salt_length,json=saltLength,proto3" json:"salt_length,omitempty"`
}

func (x *PSSOptions) Reset() {
	*x = PSSOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmcinterface_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PSSOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PSSOptions) ProtoMessage() {}

func (x *PSSOptions) ProtoReflect() protoreflect.Message {
	mi := &file_cmcinterface_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PSSOptions.ProtoReflect.Descriptor instead.
func (*PSSOptions) Descriptor() ([]byte, []int) {
	return file_cmcinterface_proto_rawDescGZIP(), []int{0}
}

func (x *PSSOptions) GetSaltLength() int32 {
	if x != nil {
		return x.SaltLength
	}
	return 0
}

type TLSSignRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content  []byte       `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Hashtype HashFunction `protobuf:"varint,3,opt,name=hashtype,proto3,enum=cmcinterface.HashFunction" json:"hashtype,omitempty"`
	PssOpts  *PSSOptions  `protobuf:"bytes,4,opt,name=pssOpts,proto3" json:"pssOpts,omitempty"`
}

func (x *TLSSignRequest) Reset() {
	*x = TLSSignRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmcinterface_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLSSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSSignRequest) ProtoMessage() {}

func (x *TLSSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmcinterface_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSSignRequest.ProtoReflect.Descriptor instead.
func (*TLSSignRequest) Descriptor() ([]byte, []int) {
	return file_cmcinterface_proto_rawDescGZIP(), []int{1}
}

func (x *TLSSignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TLSSignRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *TLSSignRequest) GetHashtype() HashFunction {
	if x != nil {
		return x.Hashtype
	}
	return HashFunction_SHA1
}

func (x *TLSSignRequest) GetPssOpts() *PSSOptions {
	if x != nil {
		return x.PssOpts
	}
	return nil
}

type TLSSignResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status        Status `protobuf:"varint,1,opt,name=status,proto3,enum=cmcinterface.Status" json:"status,omitempty"`
	SignedContent []byte `protobuf:"bytes,2,opt,name=signed_content,json=signedContent,proto3" json:"signed_content,omitempty"`
}

func (x *TLSSignResponse) Reset() {
	*x = TLSSignResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmcinterface_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLSSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSSignResponse) ProtoMessage() {}

func (x *TLSSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmcinterface_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSSignResponse.ProtoReflect.Descriptor instead.
func (*TLSSignResponse) Descriptor() ([]byte, []int) {
	return file_cmcinterface_proto_rawDescGZIP(), []int{2}
}

func (x *TLSSignResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *TLSSignResponse) GetSignedContent() []byte {
	if x != nil {
		return x.SignedContent
	}
	return nil
}

type TLSCertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TLSCertRequest) Reset() {
	*x = TLSCertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmcinterface_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLSCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSCertRequest) ProtoMessage() {}

func (x *TLSCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmcinterface_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSCertRequest.ProtoReflect.Descriptor instead.
func (*TLSCertRequest) Descriptor() ([]byte, []int) {
	return file_cmcinterface_proto_rawDescGZIP(), []int{3}
}

func (x *TLSCertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TLSCertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      Status   `protobuf:"varint,1,opt,name=status,proto3,enum=cmcinterface.Status" json:"status,omitempty"`
	Certificate [][]byte `protobuf:"bytes,2,rep,name=certificate,proto3" json:"certificate,omitempty"` // PEM encoded, separated by line
}

func (x *TLSCertResponse) Reset() {
	*x = TLSCertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmcinterface_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLSCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSCertResponse) ProtoMessage() {}

func (x *TLSCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmcinterface_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSCertResponse.ProtoReflect.Descriptor instead.
func (*TLSCertResponse) Descriptor() ([]byte, []int) {
	return file_cmcinterface_proto_rawDescGZIP(), []int{4}
}

func (x *TLSCertResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *TLSCertResponse) GetCertificate() [][]byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type AttestationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nonce []byte `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *AttestationRequest) Reset() {
	*x = AttestationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmcinterface_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationRequest) ProtoMessage() {}

func (x *AttestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmcinterface_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationRequest.ProtoReflect.Descriptor instead.
func (*AttestationRequest) Descriptor() ([]byte, []int) {
	return file_cmcinterface_proto_rawDescGZIP(), []int{5}
}

func (x *AttestationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AttestationRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type AttestationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status            Status `protobuf:"varint,1,opt,name=status,proto3,enum=cmcinterface.Status" json:"status,omitempty"`
	AttestationReport []byte `protobuf:"bytes,2,opt,name=attestation_report,json=attestationReport,proto3" json:"attestation_report,omitempty"`
}

func (x *AttestationResponse) Reset() {
	*x = AttestationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmcinterface_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationResponse) ProtoMessage() {}

func (x *AttestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmcinterface_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationResponse.ProtoReflect.Descriptor instead.
func (*AttestationResponse) Descriptor() ([]byte, []int) {
	return file_cmcinterface_proto_rawDescGZIP(), []int{6}
}

func (x *AttestationResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *AttestationResponse) GetAttestationReport() []byte {
	if x != nil {
		return x.AttestationReport
	}
	return nil
}

type VerificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce             []byte `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	AttestationReport []byte `protobuf:"bytes,2,opt,name=attestation_report,json=attestationReport,proto3" json:"attestation_report,omitempty"`
	Ca                []byte `protobuf:"bytes,3,opt,name=ca,proto3" json:"ca,omitempty"`
	Policies          []byte `protobuf:"bytes,4,opt,name=policies,proto3" json:"policies,omitempty"`
}

func (x *VerificationRequest) Reset() {
	*x = VerificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmcinterface_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationRequest) ProtoMessage() {}

func (x *VerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmcinterface_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationRequest.ProtoReflect.Descriptor instead.
func (*VerificationRequest) Descriptor() ([]byte, []int) {
	return file_cmcinterface_proto_rawDescGZIP(), []int{7}
}

func (x *VerificationRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *VerificationRequest) GetAttestationReport() []byte {
	if x != nil {
		return x.AttestationReport
	}
	return nil
}

func (x *VerificationRequest) GetCa() []byte {
	if x != nil {
		return x.Ca
	}
	return nil
}

func (x *VerificationRequest) GetPolicies() []byte {
	if x != nil {
		return x.Policies
	}
	return nil
}

type VerificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status             Status `protobuf:"varint,1,opt,name=status,proto3,enum=cmcinterface.Status" json:"status,omitempty"`
	VerificationResult []byte `protobuf:"bytes,2,opt,name=verification_result,json=verificationResult,proto3" json:"verification_result,omitempty"`
}

func (x *VerificationResponse) Reset() {
	*x = VerificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmcinterface_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationResponse) ProtoMessage() {}

func (x *VerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmcinterface_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationResponse.ProtoReflect.Descriptor instead.
func (*VerificationResponse) Descriptor() ([]byte, []int) {
	return file_cmcinterface_proto_rawDescGZIP(), []int{8}
}

func (x *VerificationResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *VerificationResponse) GetVerificationResult() []byte {
	if x != nil {
		return x.VerificationResult
	}
	return nil
}

var File_cmcinterface_proto protoreflect.FileDescriptor

var file_cmcinterface_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6d, 0x63, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6d, 0x63, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x22, 0x2d, 0x0a, 0x0a, 0x50, 0x53, 0x53, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61, 0x6c, 0x74, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x61, 0x6c, 0x74, 0x4c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x22, 0xa6, 0x01, 0x0a, 0x0e, 0x54, 0x4c, 0x53, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x36,
	0x0a, 0x08, 0x68, 0x61, 0x73, 0x68, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1a, 0x2e, 0x63, 0x6d, 0x63, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e,
	0x48, 0x61, 0x73, 0x68, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x68, 0x61,
	0x73, 0x68, 0x74, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x70, 0x73, 0x73, 0x4f, 0x70, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6d, 0x63, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x53, 0x53, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x07, 0x70, 0x73, 0x73, 0x4f, 0x70, 0x74, 0x73, 0x22, 0x66, 0x0a, 0x0f, 0x54, 0x4c,
	0x53, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e,
	0x63, 0x6d, 0x63, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x73,
	0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0d, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x22, 0x20, 0x0a, 0x0e, 0x54, 0x4c, 0x53, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x61, 0x0a, 0x0f, 0x54, 0x4c, 0x53, 0x43, 0x65, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x6d, 0x63, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x22, 0x3a, 0x0a, 0x12, 0x41, 0x74, 0x74, 0x65, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6e, 0x6f,
	0x6e, 0x63, 0x65, 0x22, 0x72, 0x0a, 0x13, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x6d, 0x63,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2d, 0x0a, 0x12, 0x61, 0x74, 0x74, 0x65,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x86, 0x01, 0x0a, 0x13, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x11, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x63, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73,
	0x22, 0x75, 0x0a, 0x14, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x6d, 0x63, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2f, 0x0a, 0x13, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x12, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x2f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49,
	0x4c, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4e, 0x4f, 0x54, 0x5f, 0x49, 0x4d, 0x50, 0x4c, 0x45,
	0x4d, 0x45, 0x4e, 0x54, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x92, 0x02, 0x0a, 0x0c, 0x48, 0x61, 0x73,
	0x68, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x48, 0x41,
	0x31, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x48, 0x41, 0x32, 0x32, 0x34, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53,
	0x48, 0x41, 0x33, 0x38, 0x34, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x48, 0x41, 0x35, 0x31,
	0x32, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x44, 0x34, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03,
	0x4d, 0x44, 0x35, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x44, 0x35, 0x53, 0x48, 0x41, 0x31,
	0x10, 0x07, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x49, 0x50, 0x45, 0x4d, 0x44, 0x31, 0x36, 0x30, 0x10,
	0x08, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x48, 0x41, 0x33, 0x5f, 0x32, 0x32, 0x34, 0x10, 0x09, 0x12,
	0x0c, 0x0a, 0x08, 0x53, 0x48, 0x41, 0x33, 0x5f, 0x32, 0x35, 0x36, 0x10, 0x0a, 0x12, 0x0c, 0x0a,
	0x08, 0x53, 0x48, 0x41, 0x33, 0x5f, 0x33, 0x38, 0x34, 0x10, 0x0b, 0x12, 0x0c, 0x0a, 0x08, 0x53,
	0x48, 0x41, 0x33, 0x5f, 0x35, 0x31, 0x32, 0x10, 0x0c, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x48, 0x41,
	0x35, 0x31, 0x32, 0x5f, 0x32, 0x32, 0x34, 0x10, 0x0d, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x48, 0x41,
	0x35, 0x31, 0x32, 0x5f, 0x32, 0x35, 0x36, 0x10, 0x0e, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x4c, 0x41,
	0x4b, 0x45, 0x32, 0x73, 0x5f, 0x32, 0x35, 0x36, 0x10, 0x0f, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x4c,
	0x41, 0x4b, 0x45, 0x32, 0x62, 0x5f, 0x32, 0x35, 0x36, 0x10, 0x10, 0x12, 0x0f, 0x0a, 0x0b, 0x42,
	0x4c, 0x41, 0x4b, 0x45, 0x32, 0x62, 0x5f, 0x33, 0x38, 0x34, 0x10, 0x11, 0x12, 0x0f, 0x0a, 0x0b,
	0x42, 0x4c, 0x41, 0x4b, 0x45, 0x32, 0x62, 0x5f, 0x35, 0x31, 0x32, 0x10, 0x12, 0x32, 0xc4, 0x02,
	0x0a, 0x0a, 0x43, 0x4d, 0x43, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x07,
	0x54, 0x4c, 0x53, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x1c, 0x2e, 0x63, 0x6d, 0x63, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x54, 0x4c, 0x53, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6d, 0x63, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x2e, 0x54, 0x4c, 0x53, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x07, 0x54, 0x4c, 0x53, 0x43, 0x65, 0x72,
	0x74, 0x12, 0x1c, 0x2e, 0x63, 0x6d, 0x63, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x2e, 0x54, 0x4c, 0x53, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x63, 0x6d, 0x63, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x54,
	0x4c, 0x53, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4f, 0x0a, 0x06, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x63, 0x6d, 0x63,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63,
	0x6d, 0x63, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x41, 0x74, 0x74, 0x65,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x51, 0x0a, 0x06, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x21, 0x2e, 0x63, 0x6d,
	0x63, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x63, 0x6d, 0x63, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x3b, 0x63, 0x6d, 0x63, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmcinterface_proto_rawDescOnce sync.Once
	file_cmcinterface_proto_rawDescData = file_cmcinterface_proto_rawDesc
)

func file_cmcinterface_proto_rawDescGZIP() []byte {
	file_cmcinterface_proto_rawDescOnce.Do(func() {
		file_cmcinterface_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmcinterface_proto_rawDescData)
	})
	return file_cmcinterface_proto_rawDescData
}

var file_cmcinterface_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cmcinterface_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cmcinterface_proto_goTypes = []interface{}{
	(Status)(0),                  // 0: cmcinterface.Status
	(HashFunction)(0),            // 1: cmcinterface.HashFunction
	(*PSSOptions)(nil),           // 2: cmcinterface.PSSOptions
	(*TLSSignRequest)(nil),       // 3: cmcinterface.TLSSignRequest
	(*TLSSignResponse)(nil),      // 4: cmcinterface.TLSSignResponse
	(*TLSCertRequest)(nil),       // 5: cmcinterface.TLSCertRequest
	(*TLSCertResponse)(nil),      // 6: cmcinterface.TLSCertResponse
	(*AttestationRequest)(nil),   // 7: cmcinterface.AttestationRequest
	(*AttestationResponse)(nil),  // 8: cmcinterface.AttestationResponse
	(*VerificationRequest)(nil),  // 9: cmcinterface.VerificationRequest
	(*VerificationResponse)(nil), // 10: cmcinterface.VerificationResponse
}
var file_cmcinterface_proto_depIdxs = []int32{
	1,  // 0: cmcinterface.TLSSignRequest.hashtype:type_name -> cmcinterface.HashFunction
	2,  // 1: cmcinterface.TLSSignRequest.pssOpts:type_name -> cmcinterface.PSSOptions
	0,  // 2: cmcinterface.TLSSignResponse.status:type_name -> cmcinterface.Status
	0,  // 3: cmcinterface.TLSCertResponse.status:type_name -> cmcinterface.Status
	0,  // 4: cmcinterface.AttestationResponse.status:type_name -> cmcinterface.Status
	0,  // 5: cmcinterface.VerificationResponse.status:type_name -> cmcinterface.Status
	3,  // 6: cmcinterface.CMCService.TLSSign:input_type -> cmcinterface.TLSSignRequest
	5,  // 7: cmcinterface.CMCService.TLSCert:input_type -> cmcinterface.TLSCertRequest
	7,  // 8: cmcinterface.CMCService.Attest:input_type -> cmcinterface.AttestationRequest
	9,  // 9: cmcinterface.CMCService.Verify:input_type -> cmcinterface.VerificationRequest
	4,  // 10: cmcinterface.CMCService.TLSSign:output_type -> cmcinterface.TLSSignResponse
	6,  // 11: cmcinterface.CMCService.TLSCert:output_type -> cmcinterface.TLSCertResponse
	8,  // 12: cmcinterface.CMCService.Attest:output_type -> cmcinterface.AttestationResponse
	10, // 13: cmcinterface.CMCService.Verify:output_type -> cmcinterface.VerificationResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_cmcinterface_proto_init() }
func file_cmcinterface_proto_init() {
	if File_cmcinterface_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmcinterface_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PSSOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmcinterface_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TLSSignRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmcinterface_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TLSSignResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmcinterface_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TLSCertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmcinterface_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TLSCertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmcinterface_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttestationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmcinterface_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttestationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmcinterface_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmcinterface_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmcinterface_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmcinterface_proto_goTypes,
		DependencyIndexes: file_cmcinterface_proto_depIdxs,
		EnumInfos:         file_cmcinterface_proto_enumTypes,
		MessageInfos:      file_cmcinterface_proto_msgTypes,
	}.Build()
	File_cmcinterface_proto = out.File
	file_cmcinterface_proto_rawDesc = nil
	file_cmcinterface_proto_goTypes = nil
	file_cmcinterface_proto_depIdxs = nil
}
