#!/bin/bash

set -euo pipefail

trap '[ $? -eq 0 ] && exit 0; printf "%s failed\n" "$0"' EXIT
dir="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"
source "${dir}/utils.sh"
export PATH=${PATH}:${HOME}/go/bin

"${dir}/generate-device-description" "$@"

"${dir}/generate-rtm-manifest-tpm" "$@"

"${dir}/generate-os-manifest-tpm" "$@"

"${dir}/generate-app-manifest-live-tpm" "$@"

"${dir}/generate-container-manifest" "$@" "ubuntu:24.04" "${dir}/../cmc" "docker"
