#!/bin/bash

set -e

DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)"
CMC_DIR="$DIR/.."

PCP="$CMC_DIR/ids-pcp"
OUT="$DIR/pki"

print_usage() {
  printf "Usage: ./setup_ids_pki [-p <dir with pcp tool>] [-o <output-dir] [-h]\n"
}

while getopts 'p:o:h' flag; do
  case "${flag}" in
    p)
        PCP="${OPTARG}"
        ;;
    o)
        OUT="${OPTARG}"
        ;;
    h)
        print_usage
        exit 1
        ;;
    *) print_usage
       exit 1 ;;
  esac
done

if [ ! -d "$PCP" ]; then
    echo "PCP tool directory $PCP does not exist"
    exit 1
fi

echo "Using $PCP as pcp directory"
echo "Using $OUT as output directory"

mkdir -p $OUT

# Setup PKI with root CA and two SubCAs (one for users, one for devices)
"$PCP"/pcp.sh "$OUT" ca

# Generate user certificates as required
gen () {
  "$PCP"/pcp.sh "$OUT" gen "$@"
}

gen developer developer_A
gen developer developer_B

gen operator operator_A
gen developer operator_B

gen evaluator evaluator_A
gen evaluator evaluator_B

gen certifier certifier_A
gen certifier certifier_B
