#!/bin/bash

set -euo pipefail

trap '[ $? -eq 0 ] && exit 0; printf "%s failed\n" "$0"' EXIT
dir="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"
source "${dir}/utils.sh"
export PATH=${PATH}:${HOME}/go/bin

if [[ "$#" -ne 2 ]]; then
   echo "Usage: ./update-app-manifest-live <data-folder> <cbor|json>"
   exit 1
fi

data=$(set -e; abs_path "$1")
input="${data}/metadata-raw"
tmp="${data}/metadata-tmp"
out="${data}/metadata-signed"
ser="${2}"

name="de.test.host-apps"

if [[ ! -d "${data}" ]]; then
  echo "Data directory ${data} does not exist. Did you run the setup-full-simple script? Abort.."
  exit 1
fi

echo "Using ${data} as directory for local data"

# Parse the IMA measurement lists
referenceValues=$(sudo parse-ima-pcr)

# App Manifest: Delete existing reference values
json=$(cat "${data}/metadata-raw/app.manifest.json")
json=$(echo "${json}" | jq 'del(.referenceValues[])')

# App Manifest: Insert new reference values
while IFS= read -r element; do
    json=$(echo "${json}" | jq --argjson element "${element}" '.referenceValues += [$element]')
done < <(echo "${referenceValues}" | jq -c '.[]')

# App Manifest: Set name
json=$(echo "${json}" | jq ".name = \"${name}\"")

# App Manifest: Store
echo "Writing ${input}/app.manifest.json"
printf "%s\n" "${json}" > "${data}/metadata-raw/app.manifest.json"

# App Description: Create corresponding app description
appdesc=$(cat "${input}/app.description.json")
appdesc=$(echo "${appdesc}" | jq ".name = \"${name}.description\"")
appdesc=$(echo "${appdesc}" | jq ".appManifest = \"${name}\"")

# Device Description: Add/replace app description to/in device description
devdesc=$(cat "${input}/device.description.json")
exists=$(echo "${devdesc}" | jq "any(.appDescriptions[]; .name == \"${name}.description\")")
if [[ "${exists}" = false ]]; then
  echo "Adding app description to device description"
else
  echo "Replacing existing app description"
  devdesc=$(echo "$devdesc" | jq ".appDescriptions |= map(select(.name != \"${name}.description\"))")
fi
devdesc=$(echo "${devdesc}" | jq --argjson desc "[${appdesc}]" '.appDescriptions += $desc')

# Device Description: Store
echo "Writing ${input}/device.description.json"
printf "%s\n" "${devdesc}" > "${input}/device.description.json"

# Sign the metadata*
key="${data}/pki/signing-cert-key.pem"
chain="${data}/pki/signing-cert.pem,${data}/pki/ca.pem"

rm -rf "${tmp}"/app.manifest.*
rm -rf "${out}"/app.manifest.*

# Convert to CBOR if specified
if [[ "${ser,,}" = "json" ]]; then
  echo "using json serialization"
  cp "${input}/app.manifest.json" "${tmp}/app.manifest.json"
  cp "${input}/device.description.json" "${tmp}/device.description.json"
elif [[ "${ser,,}" = "cbor" ]]; then
  echo "using cbor serialiation"
  cmc-converter -in "${input}/app.manifest.json" -out "${tmp}/app.manifest.cbor" -outform cbor
  cmc-converter -in "${input}/device.description.json" -out "${tmp}/device.description.cbor" -outform cbor
else
  echo "serialization format ${ser} is not supported"
  exit 1
fi

cmc-signing-tool -in "${tmp}/app.manifest.${ser}" -out "${out}/app.manifest.${ser}" -keys "${key}" -x5cs "${chain}"
cmc-signing-tool -in "${tmp}/device.description.${ser}" -out "${out}/device.description.${ser}" -keys "${key}" -x5cs "${chain}"